### ISSUE TITLE
Política de Firma FacturaE v3.1

### ISSUE THREAD

**Issue by muadek** [mdiago/Irene.Solutions.Edi.Babel#1]
Buenos días.
He probado el código que aparece en la página de inicio y el validador de http://sedeaplicaciones2.minetur.gob.es/FacturaE/index.jsp
me da el siguiente error: "Política inválida: Política de Firma FacturaE v3.1"
Además he intentado probar el que está subido en NuGet, a pesar de que mi aplicación es .net framework, y me da el siguiente error al firmar, con lo cual no puedo comprobar que me valide la firma.
![error babel](https://user-images.githubusercontent.com/50589087/171626966-51285450-0625-4626-8f9f-2b76affd1cbf.png)
¿Se me esta pasando algo? ¿o es un problema?

**Comment by mdiago** [comment]
Hola muadek, acabo de probar el código de inicio firmando con mi certificado de la FNMT  y la validación me da correcta:

![image](https://user-images.githubusercontent.com/22330809/171647085-d398e079-a9fd-4bd6-8fc3-f998eb76863c.png)

¿ Podrías enviarme el xml para que lo examine ?

**Comment by mdiago** [comment]
Parece ser que la firma con certificados de representante de la FMNT resulta no válida en este validador. Hemos incluido todos los certificados de la cadena de certificados, en el bloque X509Data. Probando tras la modificación la validación resulta correcta.

**Comment by mdiago** [comment]
Solucionado
